name: Deploy static site to server

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH and rsync
        run: |
          # 设置 SSH 环境
          mkdir -p ~/.ssh
          echo "${{ secrets.TENCENT_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # 添加远程主机 SSH 指纹
          ssh-keyscan -p 22 -H "${{ secrets.TENCENT_SSH_HOST }}" >> ~/.ssh/known_hosts

          # 测试 SSH 是否连通
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.TENCENT_SSH_USER }}@${{ secrets.TENCENT_SSH_HOST }} "echo SSH connected"

          # 部署
          echo "Starting rsync deployment..."
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" ./ ${{ secrets.TENCENT_SSH_USER }}@${{ secrets.TENCENT_SSH_HOST }}:/data/wwwroot/webtech.wiki/
